ARG BASE_IMAGE=oraclelinux:7-slim
FROM ${BASE_IMAGE}

RUN yum -y install \
      rpm-build rpm-sign rpmdevtools \
      gcc gcc-c++ make perl perl-core \
      zlib-devel \
      tar gzip unzip zip \
      findutils file which patch diffutils \
    && yum clean all && rm -rf /var/cache/yum

WORKDIR /workspace
